CREATE TABLE "GC_CONFERENCIA"
  (
  "ID" NUMBER(8,0) NOT NULL ENABLE,
  "TITULO" VARCHAR2(30) NOT NULL ENABLE,
  "ASSUNTO" VARCHAR2(60) NOT NULL ENABLE,
  "ORGANIZADOR" VARCHAR2(30) NOT NULL ENABLE,
  "DATA_INICIO" TIMESTAMP(6) NOT NULL ENABLE,
  "DATA_FIM" TIMESTAMP(6) NOT NULL ENABLE,
  CONSTRAINT "GC_CONFERENCIA_PK" PRIMARY KEY ("ID") ENABLE
  );


CREATE SEQUENCE "GC_CONFERENCIA_SEQ"
  MINVALUE 1
  INCREMENT BY 1 START WITH 1
  CACHE 20 NOORDER NOCYCLE;
  
  CREATE TABLE "GC_PALESTRANTE"
  (
  "ID" NUMBER(8,0) NOT NULL ENABLE,
  "NOME" VARCHAR2(60) NOT NULL ENABLE,
  "TITULO" VARCHAR2(30) NOT NULL ENABLE,
  "EMAIL" VARCHAR2(50) NOT NULL ENABLE,
  "BIOGRAFIA" VARCHAR(300) NOT NULL ENABLE,
  CONSTRAINT "GC_PALESTRANTE_PK" PRIMARY KEY ("ID") ENABLE
  );
  
  CREATE SEQUENCE "GC_PALESTRANTE_SEQ"
  MINVALUE 1
  INCREMENT BY 1 START WITH 1
  CACHE 20 NOORDER NOCYCLE;
                            
                            
                            
CREATE TABLE "GC_CONFERENCIA"
(
  "ID" NUMBER(8,0) NOT NULL ENABLE,
  "TITULO" VARCHAR2(30) NOT NULL ENABLE,
  "ASSUNTO" VARCHAR2(60) NOT NULL ENABLE,
  "ORGANIZADOR" VARCHAR2(30) NOT NULL ENABLE,
  "DATA_INICIO" TIMESTAMP(6) NOT NULL ENABLE,
  "DATA_FIM" TIMESTAMP(6) NOT NULL ENABLE,
  CONSTRAINT "GC_CONFERENCIA_PK" PRIMARY KEY ("ID") ENABLE
  );


insert into GC_CONFERENCIA 
values (1,'Hello World', 'CIT', 'Conferencia Legal', 
	TIMESTAMP '2070-01-01 00:00:01', TIMESTAMP '2070-01-01 00:00:01'
	);


insert into GC_CONFERENCIA 
values (GC_CONFERENCIA_SEQ.nextVal,
       'Hello World', 'CIT', 'Conferencia Legal', 
        TIMESTAMP '2070-01-01 00:00:01', TIMESTAMP '2070-01-01 00:00:01'
	);

select GC_CONFERENCIA_SEQ.NEXTVAL FROM DUAL;
